server:
  port: 1234
  shutdown: graceful

database:
  target:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: user
      password: changeme
      maximumPoolSize: 5
      poolName: postgres
      driver-class-name: org.postgresql.Driver

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
